version: '3.8'

services:
  app:
    build: .
    container_name: tug-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - tug-network
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:3rYQDq9CJHXzoZsd9uKXibqLVJLamxWfnCJNBFRtsNo=

  db:
    image: mysql:8.0
    container_name: tug-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tug_api
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - tug-mysql:/var/lib/mysql
    networks:
      - tug-network

  nginx:
    image: nginx:latest
    container_name: tug-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - tug-network

networks:
  tug-network:

volumes:
  tug-mysql: